From yfzhang/elasticsearch-ik

MAINTAINER sunzhongyuan "sunzhongyuan@zhuangtu.net"

RUN echo "################################## Enable Dynamic Scripting  ################################" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "script.inline: true" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "script.indexed: true" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "script.engine.groovy.inline.aggs: true" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "script.engine.groovy.inline.update: true" >> /usr/share/elasticsearch/config/elasticsearch.yml
